# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: scan de seguranca veracode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build com Maven
      run: mvn -B package --file pom.xml
      #run: mvn -B -DskipTests clean package
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Execução de testes com Maven
      run: mvn test
      
    - name: Veracode Upload And Scan
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
        # appname
        appname: treinamento
        # createprofile 
        createprofile: true
        # filepath
        filepath: .
        # version
        version: ${{ github.run_id }}
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        # true or flase
        createsandbox: true
        # name of the sandbox
        sandboxname: veracodescantest
        # wait X minutes for the scan to complete
        scantimeout: 60
